[package]
name = "zeebe-client"
version = "0.0.1"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
grpc = "0.6.1"
protobuf = "2"

[build-dependencies]
protoc-rust-grpc = "0.6.1"
